sudo: false
language: node_js
notifications:
  email:
    - dengfuping_develop@163.com
node_js:
  - 10
script:
  - npm run lint
  - npm run build
deploy:
  provider: surge
  project: ./dist/
  skip_cleanup: true
  domain: hasantvpassedechartsyet.surge.sh
  on:
    branch: master
